### ISSUE TITLE
problem executing

### ISSUE THREAD

**Issue by Warfenix** [kartikkhullar/Attendance100#5]
Hello!

I have configured the .csv file and I have created the .bat file with the information that is due in the readme.md but, when I run this .bat file it closes and does nothing, but instead when I directly open the attendace100.py file if that works correctly and starts the meetings.

any idea why '?

**Comment by kartikkhullar** [comment]
My bad, the Readme needs to updated. Alot of changes were pushed to this repo after the inital readme was written.
No need of creating any bat file since UI was created for selecting 'timetable file' for automation instead of passing it through a command in a bat file.
The batch file was created to save the command required to run the python script which passes in 'timetable file' as a command line argument. Since this work is now done by UI itself, so command line arguments were removed from the script.
I will update the Readme shortly.
